package domain.enums;

public enum HelpType {
    TRANSCRIPT_FOR_SEMESTER,
    TRANSCRIPT_FOR_YEAR,
    CERTIFICATE_OF_EDUCATION,
    ACADEMIC_MOBILITY,
    COORDINATION_OF_DIPLOMA_TOPIC,
    REQUEST_FOR_CREATING_ORGANIZATION
}
