package enums;

public enum HelpType {
    TRANSCRIPT_FOR_SEMESTER,
    TRANSCRIPT_FOR_YEAR,
    TRANSCRIPT_FOR_ENTIRE_STUDY,
    CERTIFICATE_OF_EDUCATION,
    ACADEMIC_MOBILITY,
    COORDINATION_OF_DIPLOMA_TOPIC,
    WORKAROUND_SHEET,
    RESTORING_ONAY_CARD,
    HELP_DEPARTMENT_OF_DEFENSE,
    HELP_LARGE_FAMILIES,
    HELP_LOSS_OF_BREADWINNER,
    HELP_FINANCING_KAZENERGY,
    INFORMATION_ABOUT_PLACE_OF_REQUIREMENT,
    REQUEST_FOR_CREATING_ORGANIZATION
}
